### ISSUE TITLE
`network.discovery` is null in leave

### ISSUE THREAD

**Issue by andrewosh** [hyperswarm/hyperswarm#30]
I just got this trace with calling `close` on a hyperswarm instance-- it might not be a bug inside hyperswarm, but some of the recent refactoring might be responsible.

```
/home/andrewosh/Development/megastore-swarm-networking/node_modules/hyperswarm/swarm.js:164
    const domain = network.discovery._domain(key)
                                     ^

TypeError: Cannot read property '_domain' of null
    at Swarm.leave (/home/andrewosh/Development/megastore-swarm-networking/node_modules/hyperswarm/swarm.js:164:38)
    at SwarmNetworker.unseed (/home/andrewosh/Development/megastore-swarm-networking/index.js:124:17)
    at Object.close (/home/andrewosh/Development/random-access-megastore/index.js:193:25)
    at defaultCore.ready.err (/home/andrewosh/Development/random-access-megastore/test/all.js:123:13)
    at /home/andrewosh/Development/random-access-megastore/node_modules/hypercore/index.js:206:15
    at apply (/home/andrewosh/Development/random-access-megastore/node_modules/thunky/index.js:44:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! Test failed.  See above for more details.
```

**Comment by davidmarkclements** [comment]
Looks like a bug - was close called before bind or was it called twice? If
this.network is null it’s not been either not been initialised or its been
destroyed. Obviously it’s still a bug and needs to be guarded

**Comment by mafintosh** [comment]
This os fixed in my latest patch

**Comment by pfrazee** [comment]
dang you had to patch the whole os to fix this?

**Comment by mafintosh** [comment]
Next time I’ll come switch your laptop!

**Comment by pfrazee** [comment]
oh dang that's some next level service for a protocol company
